config/routes.rb
Spike::Application.routes.draw do
  resources :covers

  root 'covers#index'

end

app/models/cover.rb
class Cover < ActiveRecord::Base
  include Flex::ModelIndexer
  flex.sync self

  store_accessor :settings, :favorite_color, :time_zone

  mount_uploader :image, ImageUploader

  before_create :default_name

  def default_name
    self.title ||= File.basename(image.filename, '.*').titleize if image
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/covers_controller.rb
class CoversController < ApplicationController
  before_action :set_cover, only: [:show, :edit, :update, :destroy]

  # GET /covers
  # GET /covers.json
  def index
    @covers = Cover.all
  end

  # GET /covers/1
  # GET /covers/1.json
  def show
  end

  # GET /covers/new
  def new
    @cover = Cover.new
  end

  # GET /covers/1/edit
  def edit
  end

  # POST /covers
  # POST /covers.json
  def create
    @cover = Cover.new(cover_params)

    respond_to do |format|
      if @cover.save
        format.html { redirect_to @cover, notice: 'Cover was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cover }
        format.js   {   }
      else
        format.html { render action: 'new' }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
        format.js   {  }
      end
    end
  end

  # PATCH/PUT /covers/1
  # PATCH/PUT /covers/1.json
  def update
    respond_to do |format|
      if @cover.update(cover_params)
        format.html { redirect_to @cover, notice: 'Cover was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covers/1
  # DELETE /covers/1.json
  def destroy
    @cover.destroy
    respond_to do |format|
      format.html { redirect_to covers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cover
      @cover = Cover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cover_params
      params.require(:cover).permit(:title, :subtitle, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/views/covers/_cover.html.erb
<div class="cover">
  <div><%= image_tag(cover.image_url(:thumb)) if cover.image? %></div>
  <div class="title"><%= link_to cover.title, cover_path(cover) %></div>
  <div class="subtitle"><%= cover.subtitle %></div>
  <div><%=l cover.created_at %></div>
  <div class="actions">
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_cover_path(cover), :class => 'btn btn-mini' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                cover_path(cover),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-mini btn-danger' %>
  </div>
</div>

app/views/covers/_form.html.erb
<%= form_for @cover, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subtitle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subtitle, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
      <%= f.label :image, :class => 'control-label' %>
      <div class="controls">
        <%= image_tag(@cover.image_url(:thumb)) if @cover.image? %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), covers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/covers/create.js.erb
<% if @cover.new_record? %>
  alert("Failed to upload painting: <%= j @cover.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#covers").append("<%= j render(@cover) %>");
<% end %>

app/views/covers/edit.html.erb
<%- model_class = Cover -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/covers/index.html.erb
<%- model_class = Cover -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div id="covers">
  <%= render @covers %>
</div>      
<div class="clear"></div>      

<%= form_for Cover.new do |f| %>
  <%= f.label :image, "Upload images", :class => 'btn btn-primary' %>
  <%= f.file_field :image, multiple: true, name: "cover[image]" %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/covers/new.html.erb
<%- model_class = Cover -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/covers/show.html.erb
<%- model_class = Cover -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @cover.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subtitle) %>:</strong></dt>
  <dd><%= @cover.subtitle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag(@cover.image_url(:small)) if @cover.image? %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              covers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cover_path(@cover), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cover_path(@cover),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spike</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>